name: EPIC :books:
description: Track a large task which can be split up into smaller tasks.
title: "[EPIC]: "
labels: []

body:
- type: textarea
  attributes:
    label: What?
    description: Detailed description of the large task.
  validations:
    required: true
- type: textarea
  attributes:
    label: Why?
    description: Why is this change important.
  validations:
    required: true
- type: textarea
  attributes:
    label: Solution
    description: Suggested solution, if there isn't one yet maybe a SPIKE should be the first sub-task.
- type: textarea
  attributes:
    label: Sub-Tasks
    description: Tasks which need to be complete to close this EPIC.
    value: |
      - [ ] #1
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Thanks for completing our form!
      Don't forget to select the project on the right ->
      and to then, if possible, fill in the project fields.

