name: Deploy on merged PR

on:
  workflow_call:
    secrets:
      helper_token:
        required: true
      cache_aws_key_id:
        required: true
      cache_aws_key:
        required: true
      aws_key_id:
        required: true
      aws_key:
        required: true
      aws_account:
        required: true
      slack_token:
        required: true

jobs:
  deploy_actions:
    runs-on: ubuntu-24.04
    name: Deploy Docker
    env:
      TERM: xterm-256color
      FORCE_COLOR: 2
      DOCKER_BUILDKIT: 1
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "woosmap"
          password: ${{ secrets.DOCKERHUB_RO_TOKEN }}
      - name: Getting Build-Helper Tag
        run: |
          echo "HELPER_VERSION=$(git ls-remote --tags --sort="v:refname" https://${{secrets.helper_token}}@github.com/Woosmap/build-helper.git v8.\* | awk '{print $2}' | tail -n 1)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Woosmap/build-helper
          ref: ${{ env.HELPER_VERSION }}
          token: ${{ secrets.helper_token}}
          path: helper
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Login to AWS ECR
        uses: docker/login-action@v3
        with:
          registry:  ${{ secrets.aws_account }}.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.aws_key_id }}
          password: ${{ secrets.aws_key }}
      - name: Install Bender
        run: |
          pip install --break-system-packages --extra-index-url https://pypi.fury.io/Pfii9sZDGkGXEhXEmStx/webgeoservices/ "bender==2.1.*"
      - name: Release
        uses: ./helper/.github/actions/release
        with:
          slack_token: ${{ secrets.slack_token }}
          cache_aws_key_id: ${{ secrets.cache_aws_key_id }}
          cache_aws_key: ${{ secrets.cache_aws_key }}
      - name: Deploy Develop
        uses: ./helper/.github/actions/deploy
