name: PR Checker - Are your labels correct?

on:
  workflow_call:
    secrets:
      helper_token:
        required: true

jobs:
  check_actions:
    runs-on: ubuntu-22.04
    name: PR Checker
    env:
      TERM: xterm-256color
      FORCE_COLOR: 2
      DOCKER_BUILDKIT: 1
    steps:
      - name: Getting Build-Helper Tag
        run: |
          echo "HELPER_VERSION=$(git ls-remote --tags --sort="v:refname" https://${{secrets.helper_token}}@github.com/Woosmap/build-helper.git v8.\* | awk '{print $2}' | tail -n 1)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: Woosmap/build-helper
          ref: ${{ env.HELPER_VERSION }}
          token: ${{ secrets.helper_token }}
          path: helper
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Check
        uses: ./helper/.github/actions/check