name: Smoke Test

on:
  workflow_call:
    inputs:
      env:
        description: 'Env the command was ran'
        required: true
        default: 'develop'
        type: string
      tag:
        description: 'Tag to run smoke tests for'
        required: true
        default: 'Error'
        type: string
      pr:
        description: 'Pr which set off this run'
        required: true
        default: 'Error'
        type: string
      success:
        description: 'If the deploy was successful'
        required: true
        default: '1'
        type: string
      pr_deploy:
        description: 'If running a smoke-test on a PR set to true'
        required: false
        default: 'false'
        type: string
    secrets:
      helper_token:
        required: true
      slack_token:
        required: true

jobs:
  check_actions:
    runs-on: ubuntu-22.04
    name: Smoke Test After Deploy
    env:
      TERM: xterm-256color
      FORCE_COLOR: 2
      DOCKER_BUILDKIT: 1
    steps:
      - name: Getting Build-Helper Tag
        run: |
          echo "HELPER_VERSION=$(git ls-remote --tags https://${{secrets.helper_token}}@github.com/Woosmap/build-helper.git | awk '{print $2}' | grep 'refs/tags/v7.*' | sort -nr | head -n 1)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: Woosmap/build-helper
          ref: ${{ env.HELPER_VERSION }}
          token: ${{ secrets.helper_token }}
          path: helper
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Smoke Test
        uses: ./helper/.github/actions/run_smoke_tests
        with:
          pr_deploy: ${{ inputs.pr_deploy }}
          slack_token: ${{ secrets.slack_token }}