name: Sonar scan & Deploy on merged PR

on:
  workflow_call:
    secrets:
      helper_token:
        required: true
      sonar_token:
        required: true
      cache_aws_key_id:
        required: true
      cache_aws_key:
        required: true
      aws_key_id:
        required: true
      aws_key:
        required: true
      aws_account:
        required: true
      slack_token:
        required: true

jobs:
  deploy_actions:
    runs-on: ubuntu-20.04
    name: Deploy Docker
    env:
      TERM: xterm-256color
      FORCE_COLOR: 2
      DOCKER_BUILDKIT: 1
    steps:
      - name: Getting Build-Helper Tag
        run: |
          echo "HELPER_VERSION=$(git ls-remote --tags https://${{secrets.helper_token}}@github.com/Woosmap/build-helper.git | awk '{print $2}' | grep 'refs/tags/v5.*' | sort -nr | head -n 1)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: Woosmap/build-helper
          ref: ${{ env.HELPER_VERSION }}
          token: ${{ secrets.helper_token}}
          path: helper
          fetch-depth: 1
      - name: Login to AWS ECR
        uses: docker/login-action@v1
        with:
          registry:  ${{ secrets.aws_account }}.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.aws_key_id }}
          password: ${{ secrets.aws_key }}
      - name: Install Bender
        run: |
          pip install --extra-index-url https://pypi.fury.io/Pfii9sZDGkGXEhXEmStx/webgeoservices/ "bender==0.7.*"
      - name: Destroy PR Deploy
        uses: ./helper/.github/actions/deploy
        with:
          pr_deploy: 'true'
          pr_destroy: 'true'
      - name: Release
        uses: ./helper/.github/actions/release
        with:
          slack_token: ${{ secrets.slack_token }}
          cache_aws_key_id: ${{ secrets.cache_aws_key_id }}
          cache_aws_key: ${{ secrets.cache_aws_key }}
      - name: Deploy Develop
        uses: ./helper/.github/actions/deploy
      - name: Restore code coverage cache
        uses: ./helper/.github/actions/cache
        with:
          restore: 'true'
          path: './coverage/coverage.xml'
          key: 'coverage'
          cache_aws_key_id: ${{ secrets.cache_aws_key_id }}
          cache_aws_key: ${{ secrets.cache_aws_key }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.helper_token }}
          SONAR_TOKEN: ${{ secrets.sonar_token}}
